### ISSUE TITLE
Aliasify: Syntax Error on "const"

### ISSUE THREAD

**Issue by xErik** [devongovett/brotli.js#12]
Hello!

Aliasify is complaining about `const` declarations. I suppose you used `const` for a reason and will keep it?

``` js
browserify node_modules/brotli/dec/decode.js -g aliasify -o test.js

SyntaxError: Unexpected token (26:6) (while aliasify was processing node_modules/brotli/dec/decode.js) while parsing file: node_modules/brotli/dec/decode.js
```

Thank you.

**Comment by ducret201** [comment]
Hello.

In addition, because of those `const` declarations, pdfkit can't load on  IE10.
Any chance they could be removed in source or in a build step?

Thanks

**Comment by devongovett** [comment]
sure, if you make a PR I'll merge!
