### ISSUE TITLE
brotli decompressor usage in browser?!?

### ISSUE THREAD

**Issue by jedie** [devongovett/brotli.js#2]
Is there a way to use the decompressor part in browser?

**Comment by replete** [comment]
I'm trying to figure this out myself, will let you know if I get anywhere.

It's a shame this package doesn't even have a demo.

**Comment by LeandroFavero** [comment]
Imagine in server side you compress images, js, css, and other stuff. In browser side, just download this pack, decompress and load! This will be great! Reduce download time for slow connections.

**Comment by devongovett** [comment]
You can use browserify to compile brotli to a single file for the browser, or as a part of the build for your application.

**Comment by elron** [comment]
I've tried without success
