### ISSUE TITLE
Port to JS by hand

### ISSUE THREAD

**Issue by devongovett** [devongovett/brotli.js#3]
Because the Emscripten compile is really huge, which sucks for browsers, and because it uses a ton of memory on Windows. See https://github.com/devongovett/fontkit/issues/11.

**Comment by Pomax** [comment]
I filed https://github.com/kripken/emscripten/issues/3628 to find out if this is a bug in Emscripten that can be fixed, @devongovett would you be able to generate a non-minified lib version that we can attach to the discussion there?

**Comment by devongovett** [comment]
Done, as of #6.

**Comment by Pomax** [comment]
That's amazing @devongovett, awesome work
