### ISSUE TITLE
undeclared non-core dependency

### ISSUE THREAD

**Issue by jnelson** [devongovett/brotli.js#9]
https://github.com/devongovett/brotli.js/blob/e974146a5a38c8ff00f7866a05a238a6a334012d/dec/dictionary-browser.js requires base64-js, but the dependency is not declared in package.json and it is not a core node module. I think this might be contributing to problems using PDFkit 0.8.0 in the browser.

**Comment by devongovett** [comment]
Should be fixed in v1.3.0.
